### ISSUE TITLE
Link submission: "There’s no Design, at Scale, without DesignOps"

### ISSUE THREAD

**Issue by kaelig** [DesignOps/designops-weekly-submit#24]
Very interesting!

- There’s no Design, at Scale, without DesignOps
- https://www.linkedin.com/pulse/theres-design-scale-without-designops-michael-polivka

> DesignOps is in the service of designers. It’s essentially the business of creating an ecosystem that supports bottom-up leadership by empowering them to be the best that they can be.
>
> While a newly coined term and quite a popular topic these days, DesignOps isn’t anything new. It’s evolved as a practice within creative agencies and product companies alike over the past 100 years. From print to film and TV to interactive, and now experiential and immersive experiences, each medium has carried the torch for the next in line, with design systems playing their part along the way.

**Comment by filtercake** [comment]
Nice, that should get added to the index of articles...

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
